# Generated by Django 4.2.28 on 2026-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perrera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perro',
            name='energia',
            field=models.CharField(choices=[('Poca', 'Poca'), ('Media', 'Media'), ('Mucha', 'Mucha')], default='Media', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Mediano', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
    ]
